### ISSUE TITLE
https://en.wikipedia.org/wiki/Schlumberger - article that causes crash if you read using the "full page" mode

### ISSUE THREAD

**Issue by synapse25** [shusain/read_plugin#5]

**Comment by shusain** [comment]
Did a quick profiling here and appears it ends the process quickly so it's not actually doing work that's causing a crash but there is an error looping in the console so will investigate that error to see what's failing:

![image](https://cloud.githubusercontent.com/assets/523230/24769711/12cd2b38-1acd-11e7-8187-e82c61e5d719.png)

The error causes it not to display anything

![image](https://cloud.githubusercontent.com/assets/523230/24769738/2ae949c2-1acd-11e7-8506-d4d7f4a9024f.png)

**Comment by shusain** [comment]
Take it back had a local error from refactoring fixed that one and seeing the problem now

**Comment by shusain** [comment]
After fixing the above issue see that it fails when it hits "N.V." in this sentence

> Schlumberger is incorporated in Willemstad, Curaçao as Schlumberger N.V.

Investigating exactly why it fails on the N.V.

**Comment by knod** [comment]
Thanks! I'm working on other parts of the project right now, but let me know how it goes.

**Comment by shusain** [comment]
Think this was all just a few errors in the refactoring for the new code in the playbackUI pushed a commit to fix it.  General problem was I was trying to use a function to shift letters around in strings but since they're immutable in JS the changes in the function didn't actually get reflected in the original text so it would get stuck in an infinite loop trying to skip over having punctuation in the middle and never getting to the end of the string.  Fixed by wrapping the strings in an object and reference the strings from there so when they are changed the changes are reflected in the references through the object.
